Fix server
leonicaisse/mevn-quiz pull request #14
Opened 2021-12-17 22:24 UTC by CollierAnthony

2021-12-17 22:25 UTC, CollierAnthony commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Ajouter MongoDB](https://trello.com/c/rcWgziuL/2-back-ajouter-mongodb)

2021-12-17 22:27 UTC, CollierAnthony commented
![](https://github.trello.services/images/mini-trello-icon.png) [[BACK] Refacto des fichiers pour plus de lisibilité et faciliter les tests](https://trello.com/c/qTBhOFxy/14-back-refacto-des-fichiers-pour-plus-de-lisibilit%C3%A9-et-faciliter-les-tests)

2021-12-18 10:40 UTC, leonicaisse requested changes

2021-12-18 10:40 UTC, leonicaisse commented on server/app.js
> +const mongo = require('./config/database');
Server should not be aware of the database provider, use "database" as a var name instead of "mongo"

2021-12-18 10:53 UTC, leonicaisse approved these changes

2021-12-18 10:53 UTC, merged